apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gen-hostname
  namespace: functions
spec:
  template:
    spec:
      containers:
        - image: docker.repo.<domain-name>/org/ia/faas/gen-hostname:1.0.9
 
          env:
            - name: vmwareaccount
              value: /var/secret/vmwareaccount
            - name: vmwarepassword
              value: /var/secret/vmwarepassword
 
          volumeMounts:
            - name: vmwareaccount
              mountPath: /var/secret/vmwareaccount
            - name: vmwarepassword
              mountPath: /var/secret/vmwarepassword
 
      volumes:
        - name: vmwareaccount
          secret:
            secretName: vmwareaccount
        - name: vmwarepassword
          secret:
            secretName: vmwarepassword
