apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: server-exists
  namespace: functions
spec:
  template:
    spec:
      containers:
        - image: docker.repo.<domain-name>/org/ia/faas/server-exists:1.0.8
