---
- name: Ensure ADGroup
  gather_facts: no
  hosts: ics_domain_controller:&prod:&taylor[0]

  tasks:
  - name: ensure a group exists
    win_domain_group:
      name: {{ adgroup_name }}
      scope: global
      organizational_unit: OU=infrastructure,DC=corpgroups,DC=org,DC=com
      state: absent

  - name: ensure computer object exists in target OU
    win_domain_computer:
      name: "{{ asset_name }}"
      ou: "{{ ad_ou }}"
      state: present
