apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: decom-dns
  namespace: functions
spec:
  template:
    spec:
      containers:
        - image: docker.repo.<domain-name>/org/ia/faas/decom-dns:1.0.8
 
          env:
            - name: sshaccount
              value: /var/secret/sshaccount
            - name: sshpassword
              value: /var/secret/sshpassword
 
          volumeMounts:
            - name: sshaccount
              mountPath: /var/secret/sshaccount
            - name: sshpassword
              mountPath: /var/secret/sshpassword
 
      volumes:
        - name: sshaccount
          secret:
            secretName: sshaccount
        - name: sshpassword
          secret:
            secretName: sshpassword

