apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: decom-async-tasks
  namespace: functions
spec:
  template:
    spec:
      containers:
        - image: docker.repo.<domain-name>/org/ia/faas/decom-async-tasks:1.0.1
