apiVersion: "v1"
kind: "Pod"
metadata:
  annotations:
    <domain-name>/product: "jenkins"
    <domain-name>/jenkins-agent: "container"
spec:
  volumes:
    - name: "buildah-cache"
      emptyDir:
        medium: "Memory"
  containers:
  - name: "jnlp"
    image: "docker.repo.<domain-name>/org/jenkins/agent/inbound:latest"
    imagePullPolicy: "Always"
    tty: false
    resources:
      limits:
        memory: 1000Mi
        cpu: 1000m
  - name: "clientbase"
    image: "docker.repo.<domain-name>/org/tools/openshift/client/base:latest"
    imagePullPolicy: "IfNotPresent"
    tty: true
    securityConext:
      privileged: true
    resources:
      limits:
        memory: 1000Mi
        cpu: 1000m
    volumeMounts:
    - name: "buildah-cache"
      mountPath: "/var/lib/container"
      